# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Package Download

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - run: cp install/package.json package.json
      - name: Install Dependencies
        run: npm install
      - name: node_modules
        uses: actions/upload-artifact@v3
        if: success() || failure() 
        with:
          name: plugins
          path: node_modules
          if-no-files-found: error
